spring.application.name=noticeboard

# PostgreSQL 설정
spring.datasource.url=jdbc:postgresql://localhost:5432/noticeboard

# 유저네임 변수 설정 
spring.datasource.username=${DB_USERNAME}

# DB Password 변수 설정 
spring.datasource.password=${DB_PASSWORD}

# PostgreSQL 드라이버(자바 - DB 연결 역할)
spring.datasource.driver-class-name=org.postgresql.Driver

# Mybatis SQL 로그 출력
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

